require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Rails/ApplicationRecord:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

LineLength:
  Max: 120

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 100

Metrics/PerceivedComplexity:
  Max: 50

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
  Enabled: false

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

# Disabled since it only applies to Rails 5. Reenable when we migrate our apps to Rails 5.
# https://github.com/bbatsov/rubocop/issues/3629
Rails/HttpPositionalArguments:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    # These both use file-level blocks, rather then classes or modules,
    # making the block-length restriction silly.
    - 'app/graph/**/*'
    - 'spec/**/*'
    - '**/*.rake'

# Disabled since `safe_join`ing has the same security risk as `html_safe`
# but makes code far more awkward
Rails/OutputSafety:
  Enabled: false

Style/SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

# Disabled since it catches strftime incorrectly
# See https://github.com/bbatsov/rubocop/issues/5245
Style/FormatStringToken:
  Enabled: false

# safe_load is too restrictive, since we need ERB
Security/YAMLLoad:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
